---
- hosts: linuxservers
  become: yes

  tasks:
  - name: Create file
    file:
      path: /root/testfile.txt
      state: touch
  - name: Add line in file
    lineinfile:
      path: /root/testfile.txt
      line: Ansible was there - right over there. You missed it.


