---
- hosts: domaincontroller
  vars:
    domain: ansible.local

  tasks:
  - name: Create Group
    community.windows.win_domain_group:
      name: corp
      scope: global
      state: present

  - name: Create user
    community.windows.win_domain_user:
      name: pjuulex
      firstname: Peter
      surname: Juul
      password: lilleSTORT!2
      state: present
      groups:
      - corp
